apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-rollouts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo-sync-failed
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-sync
spec:
  project: fyp-project
  source:
    repoURL: git@github.com:The-Unpaid-Developers/manifest.git
    targetRevision: main
    path: k8s/kyverno_policies
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
