apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: proxy-service-rollout
  namespace: fyp
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
        # this label needs to be hard coded to the pod spec as kustomize will not patch custom resources
        # ref: https://github.com/kubernetes-sigs/kustomize/discussions/5496
        app.kubernetes.io/name: proxy-service
        # There is an addition 'version' label which will be added by 'canaryMetadata' and 'stableMetadata'
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: proxy-service
        imagePullPolicy: Always
        image: smithquaz/fyp-proxy-service:v1.0.0
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: CORE_SERVICE_URL
          value: core-service-stable:8080
        - name: DIAGRAM_SERVICE_URL
          value: diagram-service-stable:8081
        - name: CHATBOT_SERVICE_URL
          value: chatbot-service-stable:8000
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: { duration: 20s }
      - setWeight: 40
      - pause: { duration: 20s }
      - setWeight: 60
      - pause: { duration: 20s }
      - setWeight: 80
      - pause: { duration: 20s }
      - setWeight: 100
      # traffic routing using istio subset
      canaryService: proxy-service-canary
      stableService: proxy-service-stable
      trafficRouting:
        istio:
          virtualService:
            name: application-virtualservice # points to path based routing virtual service
            routes:
            - proxy-service-route # Name of the route to be used
            # TODO: add a HTTPS route

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service-stable
  namespace: fyp
spec:
  type: ClusterIP
  selector:
    app: proxy-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service-canary
  namespace: fyp
spec:
  type: ClusterIP
  selector:
    app: proxy-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
