apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: proxy-service-rollout
  namespace: fyp
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
        # this label needs to be hard coded to the pod spec as kustomize will not patch custom resources
        # ref: https://github.com/kubernetes-sigs/kustomize/discussions/5496
        app.kubernetes.io/name: proxy-service
        # There is an addition 'version' label which will be added by 'canaryMetadata' and 'stableMetadata'
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: proxy-service
        imagePullPolicy: Always
        image: smithquaz/fyp-proxy-service:1.0.0
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - CORE_SERVICE_URL=core-service:8080
        - DIAGRAM_SERVICE_URL=diagram-service:8081
        - CHATBOT_SERVICE_URL=chatbot-service:8082
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: fyp
spec:
  type: ClusterIP
  selector:
    app: proxy-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
